name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pytest=6.2.2
  - scipy=1.5.2
  - pip=20.3.3
  - pip:
      - wandb==0.12.17
      - protobuf==3.20.0
      - flask==2.1.0
      - jinja2<3.1.0
